# postgres-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  username: appuser
  password: securepassword123
  postgres-password: securepassword123
